2023-12-01 22:35:05.617 | ERROR    | utils.loggings:exception:40 - (pymysql.err.DataError) (1264, "Out of range value for column 'UserID' at row 1")
[SQL: INSERT INTO users (`UserID`, `UserName`, `RealName`, `Gender`, `IDCard`, `Email`, `Address`, `Account`, `Password`) VALUES (%(UserID)s, %(UserName)s, %(RealName)s, %(Gender)s, %(IDCard)s, %(Email)s, %(Address)s, %(Account)s, %(Password)s)]
[parameters: {'UserID': 2023120122357132, 'UserName': None, 'RealName': None, 'Gender': None, 'IDCard': None, 'Email': None, 'Address': None, 'Account': '22', 'Password': '423'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
Traceback (most recent call last):

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
    │    │       └ <function DefaultDialect.do_execute at 0x00000282CA3484C0>
    │    └ <sqlalchemy.dialects.mysql.pymysql.MySQLDialect_pymysql object at 0x00000282CA6F56F0>
    └ <sqlalchemy.engine.base.Connection object at 0x00000282CBF685E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
    │      │       │          └ {'UserID': 2023120122357132, 'UserName': None, 'RealName': None, 'Gender': None, 'IDCard': None, 'Email': None, 'Address': No...
    │      │       └ 'INSERT INTO users (`UserID`, `UserName`, `RealName`, `Gender`, `IDCard`, `Email`, `Address`, `Account`, `Password`) VALUES (...
    │      └ <function Cursor.execute at 0x00000282CB86ADD0>
    └ <pymysql.cursors.Cursor object at 0x00000282CBF6BBB0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\cursors.py", line 158, in execute
    result = self._query(query)
             │    │      └ "INSERT INTO users (`UserID`, `UserName`, `RealName`, `Gender`, `IDCard`, `Email`, `Address`, `Account`, `Password`) VALUES (...
             │    └ <function Cursor._query at 0x00000282CB86B250>
             └ <pymysql.cursors.Cursor object at 0x00000282CBF6BBB0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\cursors.py", line 325, in _query
    conn.query(q)
    │    │     └ "INSERT INTO users (`UserID`, `UserName`, `RealName`, `Gender`, `IDCard`, `Email`, `Address`, `Account`, `Password`) VALUES (...
    │    └ <function Connection.query at 0x00000282CB8BE560>
    └ <pymysql.connections.Connection object at 0x00000282CBF68A60>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
    │    │                │    │                             └ False
    │    │                │    └ <function Connection._read_query_result at 0x00000282CB8BEB90>
    │    │                └ <pymysql.connections.Connection object at 0x00000282CBF68A60>
    │    └ 0
    └ <pymysql.connections.Connection object at 0x00000282CBF68A60>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 779, in _read_query_result
    result.read()
    │      └ <function MySQLResult.read at 0x00000282CB8BF370>
    └ <pymysql.connections.MySQLResult object at 0x00000282CBE42EF0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
                   │    └ None
                   └ <pymysql.connections.MySQLResult object at 0x00000282CBE42EF0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 729, in _read_packet
    packet.raise_for_error()
    │      └ <function MysqlPacket.raise_for_error at 0x00000282CB8BD120>
    └ <pymysql.protocol.MysqlPacket object at 0x00000282CBF6A5F0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
    │   │                     │    └ <member '_data' of 'MysqlPacket' objects>
    │   │                     └ <pymysql.protocol.MysqlPacket object at 0x00000282CBF6A5F0>
    │   └ <function raise_mysql_exception at 0x00000282CA7C0550>
    └ <module 'pymysql.err' from 'C:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pymysql\\err....

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
          │          │      └ "Out of range value for column 'UserID' at row 1"
          │          └ 1264
          └ <class 'pymysql.err.DataError'>

pymysql.err.DataError: (1264, "Out of range value for column 'UserID' at row 1")


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "E:\pycharm\PyCharm2023.2.4\plugins\python\helpers\pydev\_pydev_bundle\pydev_monkey.py", line 805, in __call__
    ret = self.original_func(*self.args, **self.kwargs)
          │    │              │    │       │    └ {}
          │    │              │    │       └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x00000282CBE73940>
          │    │              │    └ ()
          │    │              └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x00000282CBE73940>
          │    └ <bound method Thread._bootstrap of <Thread(Thread-5 (serve_forever), started daemon 26092)>>
          └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x00000282CBE73940>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x00000282C689EE60>
    └ <Thread(Thread-5 (serve_forever), started daemon 26092)>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x00000282C689EB90>
    └ <Thread(Thread-5 (serve_forever), started daemon 26092)>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-5 (serve_forever), started daemon 26092)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-5 (serve_forever), started daemon 26092)>
    │    └ <bound method BaseWSGIServer.serve_forever of <werkzeug.serving.BaseWSGIServer object at 0x00000282C9641C00>>
    └ <Thread(Thread-5 (serve_forever), started daemon 26092)>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 806, in serve_forever
    super().serve_forever(poll_interval=poll_interval)
                                        └ 0.5

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 237, in serve_forever
    self._handle_request_noblock()
    │    └ <function BaseServer._handle_request_noblock at 0x00000282C6F77E20>
    └ <werkzeug.serving.BaseWSGIServer object at 0x00000282C9641C00>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
    │    │               │        └ ('127.0.0.1', 54750)
    │    │               └ <socket.socket fd=972, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=(...
    │    └ <function BaseServer.process_request at 0x00000282C87C8040>
    └ <werkzeug.serving.BaseWSGIServer object at 0x00000282C9641C00>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 54750)
    │    │              └ <socket.socket fd=972, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=(...
    │    └ <function BaseServer.finish_request at 0x00000282C87C8160>
    └ <werkzeug.serving.BaseWSGIServer object at 0x00000282C9641C00>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.BaseWSGIServer object at 0x00000282C9641C00>
    │    │                   │        └ ('127.0.0.1', 54750)
    │    │                   └ <socket.socket fd=972, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=(...
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.BaseWSGIServer object at 0x00000282C9641C00>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 747, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x00000282C97BD990>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x00000282CBE42A40>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 390, in handle
    super().handle()

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 432, in handle
    self.handle_one_request()
    │    └ <function BaseHTTPRequestHandler.handle_one_request at 0x00000282C87C9870>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x00000282CBE42A40>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 420, in handle_one_request
    method()
    └ <bound method WSGIRequestHandler.run_wsgi of <werkzeug.serving.WSGIRequestHandler object at 0x00000282CBE42A40>>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <werkzeug.debug.DebuggedApplication object at 0x00000282CBE42B00>
    │       │    └ <werkzeug.serving.BaseWSGIServer object at 0x00000282C9641C00>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x00000282CBE42A40>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x00000282CBF2D900>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 325, in execute
    for data in application_iter:
                └ <generator object DebuggedApplication.debug_application at 0x00000282CBCEFA70>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\debug\__init__.py", line 330, in debug_application
    app_iter = self.app(environ, start_response)
               │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x00000282CBF2DBD0>
               │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=972>, 'wsgi.errors': <_io.TextIOWr...
               │    └ <Flask 'app'>
               └ <werkzeug.debug.DebuggedApplication object at 0x00000282CBE42B00>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x00000282CBF2DBD0>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=972>, 'wsgi.errors': <_io.TextIOWr...
           │    └ <function Flask.wsgi_app at 0x00000282C9B03B50>
           └ <Flask 'app'>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x00000282C9B030A0>
               └ <Flask 'app'>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x00000282C9B03010>
         └ <Flask 'app'>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           │    │           │    │              │    │            └ {}
           │    │           │    │              │    └ 'users.register'
           │    │           │    │              └ <Rule '/api_1_0/users/register' (POST, OPTIONS) -> users.register>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x00000282CA702680>, 'apiversion.Apiversion': <function View.as_view...
           │    │           └ <Flask 'app'>
           │    └ <function Flask.ensure_sync at 0x00000282C9B032E0>
           └ <Flask 'app'>

  File "C:\Users\Lenovo\PycharmProjects\api_project\api\api_1_0\usersResource\urls.py", line 21, in register
    return UsersOtherResource.register()
           │                  └ <classmethod(<function UsersOtherResource.register at 0x00000282CBE23D00>)>
           └ <class 'api_1_0.usersResource.usersOtherResource.UsersOtherResource'>

  File "C:\Users\Lenovo\PycharmProjects\api_project\api\api_1_0\usersResource\usersOtherResource.py", line 52, in register
    res = UsersService.register(**kwargs)
          │            │          └ {'account': '22', 'password': '423'}
          │            └ <classmethod(<function UsersService.register at 0x00000282CBE22F80>)>
          └ <class 'service.usersService.UsersService'>

> File "C:\Users\Lenovo\PycharmProjects\api_project\api\service\usersService.py", line 66, in register
    db.session.commit()
    │  │       └ <function scoped_session.commit at 0x00000282CA66B9A0>
    │  └ <sqlalchemy.orm.scoping.scoped_session object at 0x00000282C9CBC160>
    └ <SQLAlchemy mysql+pymysql://root:***@127.0.0.1:3306/project_1?charset=utf8>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\scoping.py", line 598, in commit
    return self._proxied.commit()
           │    └ <property object at 0x00000282CA675C60>
           └ <sqlalchemy.orm.scoping.scoped_session object at 0x00000282C9CBC160>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\session.py", line 1969, in commit
    trans.commit(_to_root=True)
    │     └ <function SessionTransaction.commit at 0x00000282CA5E12D0>
    └ <sqlalchemy.orm.session.SessionTransaction object at 0x00000282CBC1DF80>

  File "<string>", line 2, in commit

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                │  │      │      └ {'_to_root': True}
                │  │      └ ()
                │  └ <sqlalchemy.orm.session.SessionTransaction object at 0x00000282CBC1DF80>
                └ <function SessionTransaction.commit at 0x00000282CA5E1240>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\session.py", line 1256, in commit
    self._prepare_impl()
    │    └ <function SessionTransaction._prepare_impl at 0x00000282CA5E11B0>
    └ <sqlalchemy.orm.session.SessionTransaction object at 0x00000282CBC1DF80>

  File "<string>", line 2, in _prepare_impl

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                │  │      │      └ {}
                │  │      └ ()
                │  └ <sqlalchemy.orm.session.SessionTransaction object at 0x00000282CBC1DF80>
                └ <function SessionTransaction._prepare_impl at 0x00000282CA5E1090>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\session.py", line 1231, in _prepare_impl
    self.session.flush()
    │    │       └ <function Session.flush at 0x00000282CA5E3D90>
    │    └ <sqlalchemy.orm.session.Session object at 0x00000282CBF68220>
    └ <sqlalchemy.orm.session.SessionTransaction object at 0x00000282CBC1DF80>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\session.py", line 4312, in flush
    self._flush(objects)
    │    │      └ None
    │    └ <function Session._flush at 0x00000282CA5E3F40>
    └ <sqlalchemy.orm.session.Session object at 0x00000282CBF68220>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\session.py", line 4447, in _flush
    with util.safe_reraise():
         │    └ <class 'sqlalchemy.util.langhelpers.safe_reraise'>
         └ <module 'sqlalchemy.util' from 'C:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sqlalchem...

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
          │         │              └ <traceback object at 0x00000282CBFDB240>
          │         └ <method 'with_traceback' of 'BaseException' objects>
          └ DataError('(pymysql.err.DataError) (1264, "Out of range value for column \'UserID\' at row 1")')

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\session.py", line 4408, in _flush
    flush_context.execute()
    │             └ <function UOWTransaction.execute at 0x00000282CA5D2170>
    └ <sqlalchemy.orm.unitofwork.UOWTransaction object at 0x00000282CBF6A9B0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
    │   │       └ <sqlalchemy.orm.unitofwork.UOWTransaction object at 0x00000282CBF6A9B0>
    │   └ <function SaveUpdateAll.execute at 0x00000282CA5D2A70>
    └ SaveUpdateAll(Mapper[Users(users)])

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
    │    │         │               └ <function save_obj at 0x00000282CA5BD000>
    │    │         └ <module 'sqlalchemy.orm.persistence' from 'C:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages...
    │    └ <module 'sqlalchemy.util.preloaded' from 'C:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\...
    └ <module 'sqlalchemy.util' from 'C:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sqlalchem...

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
    └ <function _emit_insert_statements at 0x00000282CA5BDA20>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\orm\persistence.py", line 1043, in _emit_insert_statements
    result = connection.execute(
             │          └ <function Connection.execute at 0x00000282CA2A4DC0>
             └ <sqlalchemy.engine.base.Connection object at 0x00000282CBF685E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           └ <bound method ClauseElement._execute_on_connection of <sqlalchemy.sql.dml.Insert object at 0x00000282CBF69FC0>>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           │          └ <function Connection._execute_clauseelement at 0x00000282CA2A5090>
           └ <sqlalchemy.engine.base.Connection object at 0x00000282CBF685E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
          │    └ <function Connection._execute_context at 0x00000282CA2A5240>
          └ <sqlalchemy.engine.base.Connection object at 0x00000282CBF685E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 1848, in _execute_context
    return self._exec_single_context(
           │    └ <function Connection._exec_single_context at 0x00000282CA2A52D0>
           └ <sqlalchemy.engine.base.Connection object at 0x00000282CBF685E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
    │    └ <function Connection._handle_dbapi_exception at 0x00000282CA2A5510>
    └ <sqlalchemy.engine.base.Connection object at 0x00000282CBF685E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 2343, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
          │                    │              │                 └ DataError(1264, "Out of range value for column 'UserID' at row 1")
          │                    │              └ (<class 'pymysql.err.DataError'>, DataError(1264, "Out of range value for column 'UserID' at row 1"), <traceback object at 0x...
          │                    └ <method 'with_traceback' of 'BaseException' objects>
          └ DataError('(pymysql.err.DataError) (1264, "Out of range value for column \'UserID\' at row 1")')

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
    │    │       └ <function DefaultDialect.do_execute at 0x00000282CA3484C0>
    │    └ <sqlalchemy.dialects.mysql.pymysql.MySQLDialect_pymysql object at 0x00000282CA6F56F0>
    └ <sqlalchemy.engine.base.Connection object at 0x00000282CBF685E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
    │      │       │          └ {'UserID': 2023120122357132, 'UserName': None, 'RealName': None, 'Gender': None, 'IDCard': None, 'Email': None, 'Address': No...
    │      │       └ 'INSERT INTO users (`UserID`, `UserName`, `RealName`, `Gender`, `IDCard`, `Email`, `Address`, `Account`, `Password`) VALUES (...
    │      └ <function Cursor.execute at 0x00000282CB86ADD0>
    └ <pymysql.cursors.Cursor object at 0x00000282CBF6BBB0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\cursors.py", line 158, in execute
    result = self._query(query)
             │    │      └ "INSERT INTO users (`UserID`, `UserName`, `RealName`, `Gender`, `IDCard`, `Email`, `Address`, `Account`, `Password`) VALUES (...
             │    └ <function Cursor._query at 0x00000282CB86B250>
             └ <pymysql.cursors.Cursor object at 0x00000282CBF6BBB0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\cursors.py", line 325, in _query
    conn.query(q)
    │    │     └ "INSERT INTO users (`UserID`, `UserName`, `RealName`, `Gender`, `IDCard`, `Email`, `Address`, `Account`, `Password`) VALUES (...
    │    └ <function Connection.query at 0x00000282CB8BE560>
    └ <pymysql.connections.Connection object at 0x00000282CBF68A60>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
    │    │                │    │                             └ False
    │    │                │    └ <function Connection._read_query_result at 0x00000282CB8BEB90>
    │    │                └ <pymysql.connections.Connection object at 0x00000282CBF68A60>
    │    └ 0
    └ <pymysql.connections.Connection object at 0x00000282CBF68A60>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 779, in _read_query_result
    result.read()
    │      └ <function MySQLResult.read at 0x00000282CB8BF370>
    └ <pymysql.connections.MySQLResult object at 0x00000282CBE42EF0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
                   │    └ None
                   └ <pymysql.connections.MySQLResult object at 0x00000282CBE42EF0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py", line 729, in _read_packet
    packet.raise_for_error()
    │      └ <function MysqlPacket.raise_for_error at 0x00000282CB8BD120>
    └ <pymysql.protocol.MysqlPacket object at 0x00000282CBF6A5F0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
    │   │                     │    └ <member '_data' of 'MysqlPacket' objects>
    │   │                     └ <pymysql.protocol.MysqlPacket object at 0x00000282CBF6A5F0>
    │   └ <function raise_mysql_exception at 0x00000282CA7C0550>
    └ <module 'pymysql.err' from 'C:\\Users\\Lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pymysql\\err....

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
          │          │      └ "Out of range value for column 'UserID' at row 1"
          │          └ 1264
          └ <class 'pymysql.err.DataError'>

sqlalchemy.exc.DataError: (pymysql.err.DataError) (1264, "Out of range value for column 'UserID' at row 1")
[SQL: INSERT INTO users (`UserID`, `UserName`, `RealName`, `Gender`, `IDCard`, `Email`, `Address`, `Account`, `Password`) VALUES (%(UserID)s, %(UserName)s, %(RealName)s, %(Gender)s, %(IDCard)s, %(Email)s, %(Address)s, %(Account)s, %(Password)s)]
[parameters: {'UserID': 2023120122357132, 'UserName': None, 'RealName': None, 'Gender': None, 'IDCard': None, 'Email': None, 'Address': None, 'Account': '22', 'Password': '423'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
2023-12-29 10:41:46.564 | ERROR    | utils.loggings:exception:40 - 'UsersService' object is not callable
Traceback (most recent call last):

  File "E:\pycharm\PyCharm2023.2.4\plugins\python\helpers\pydev\_pydev_bundle\pydev_monkey.py", line 805, in __call__
    ret = self.original_func(*self.args, **self.kwargs)
          │    │              │    │       │    └ {}
          │    │              │    │       └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x00000164D0ECBBB0>
          │    │              │    └ ()
          │    │              └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x00000164D0ECBBB0>
          │    └ <bound method Thread._bootstrap of <Thread(Thread-5 (serve_forever), started daemon 9056)>>
          └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x00000164D0ECBBB0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x00000164CB902E60>
    └ <Thread(Thread-5 (serve_forever), started daemon 9056)>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x00000164CB902B90>
    └ <Thread(Thread-5 (serve_forever), started daemon 9056)>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-5 (serve_forever), started daemon 9056)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-5 (serve_forever), started daemon 9056)>
    │    └ <bound method BaseWSGIServer.serve_forever of <werkzeug.serving.BaseWSGIServer object at 0x00000164CE6A60B0>>
    └ <Thread(Thread-5 (serve_forever), started daemon 9056)>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 806, in serve_forever
    super().serve_forever(poll_interval=poll_interval)
                                        └ 0.5

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 237, in serve_forever
    self._handle_request_noblock()
    │    └ <function BaseServer._handle_request_noblock at 0x00000164CBFD7E20>
    └ <werkzeug.serving.BaseWSGIServer object at 0x00000164CE6A60B0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
    │    │               │        └ ('127.0.0.1', 60023)
    │    │               └ <socket.socket fd=916, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=(...
    │    └ <function BaseServer.process_request at 0x00000164CD828040>
    └ <werkzeug.serving.BaseWSGIServer object at 0x00000164CE6A60B0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 60023)
    │    │              └ <socket.socket fd=916, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=(...
    │    └ <function BaseServer.finish_request at 0x00000164CD828160>
    └ <werkzeug.serving.BaseWSGIServer object at 0x00000164CE6A60B0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.BaseWSGIServer object at 0x00000164CE6A60B0>
    │    │                   │        └ ('127.0.0.1', 60023)
    │    │                   └ <socket.socket fd=916, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=(...
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.BaseWSGIServer object at 0x00000164CE6A60B0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 747, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x00000164CE825900>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x00000164D0ECBEE0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 390, in handle
    super().handle()

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 432, in handle
    self.handle_one_request()
    │    └ <function BaseHTTPRequestHandler.handle_one_request at 0x00000164CD829870>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x00000164D0ECBEE0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 420, in handle_one_request
    method()
    └ <bound method WSGIRequestHandler.run_wsgi of <werkzeug.serving.WSGIRequestHandler object at 0x00000164D0ECBEE0>>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <werkzeug.debug.DebuggedApplication object at 0x00000164D0E96C20>
    │       │    └ <werkzeug.serving.BaseWSGIServer object at 0x00000164CE6A60B0>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x00000164D0ECBEE0>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x00000164D0F9E3B0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 325, in execute
    for data in application_iter:
                └ <generator object DebuggedApplication.debug_application at 0x00000164D0F37CA0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\debug\__init__.py", line 330, in debug_application
    app_iter = self.app(environ, start_response)
               │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x00000164D0F9E320>
               │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=916>, 'wsgi.errors': <_io.TextIOWr...
               │    └ <Flask 'app'>
               └ <werkzeug.debug.DebuggedApplication object at 0x00000164D0E96C20>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x00000164D0F9E320>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=916>, 'wsgi.errors': <_io.TextIOWr...
           │    └ <function Flask.wsgi_app at 0x00000164CEB87AC0>
           └ <Flask 'app'>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x00000164CEB87010>
               └ <Flask 'app'>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x00000164CEB86F80>
         └ <Flask 'app'>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           │    │           │    │              │    │            └ {}
           │    │           │    │              │    └ 'users.information'
           │    │           │    │              └ <Rule '/users/information' (POST, OPTIONS) -> users.information>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x00000164CF765FC0>, 'apiversion.Apiversion': <function View.as_view...
           │    │           └ <Flask 'app'>
           │    └ <function Flask.ensure_sync at 0x00000164CEB87250>
           └ <Flask 'app'>

  File "E:\code\backend\api\api_1_0\usersResource\urls.py", line 25, in information
    return UsersOtherResource.information()
           │                  └ <classmethod(<function UsersOtherResource.information at 0x00000164D0E839A0>)>
           └ <class 'api_1_0.usersResource.usersOtherResource.UsersOtherResource'>

  File "E:\code\backend\api\api_1_0\usersResource\usersOtherResource.py", line 80, in information
    res = UsersService.information(**kwargs)
          │            │             └ {'UserID': '2023120417239418', 'RealName': 'wang', 'Gender': '男', 'IDcard': '123', 'Address': '山西省吕梁市', 'Account': '123456', ...
          │            └ <classmethod(<function UsersService.information at 0x00000164D0E82B90>)>
          └ <class 'service.usersService.UsersService'>

> File "E:\code\backend\api\service\usersService.py", line 108, in information
    existing_user(RealName=realname,Gender=gender,IDcard=idcard,Address=address,Account=account,Email=email)
    │                      │               │             │              │               │             └ '2085616045@qq.com'
    │                      │               │             │              │               └ '123456'
    │                      │               │             │              └ '山西省吕梁市'
    │                      │               │             └ '123'
    │                      │               └ '男'
    │                      └ 'wang'
    └ <UsersService 2023120417239418>

TypeError: 'UsersService' object is not callable
2023-12-29 10:43:45.290 | ERROR    | utils.loggings:exception:40 - 'UsersService' object is not callable
Traceback (most recent call last):

  File "E:\pycharm\PyCharm2023.2.4\plugins\python\helpers\pydev\_pydev_bundle\pydev_monkey.py", line 805, in __call__
    ret = self.original_func(*self.args, **self.kwargs)
          │    │              │    │       │    └ {}
          │    │              │    │       └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x0000026B3813FCD0>
          │    │              │    └ ()
          │    │              └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x0000026B3813FCD0>
          │    └ <bound method Thread._bootstrap of <Thread(Thread-5 (serve_forever), started daemon 20392)>>
          └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x0000026B3813FCD0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x0000026B32BD2E60>
    └ <Thread(Thread-5 (serve_forever), started daemon 20392)>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x0000026B32BD2B90>
    └ <Thread(Thread-5 (serve_forever), started daemon 20392)>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-5 (serve_forever), started daemon 20392)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-5 (serve_forever), started daemon 20392)>
    │    └ <bound method BaseWSGIServer.serve_forever of <werkzeug.serving.BaseWSGIServer object at 0x0000026B359260E0>>
    └ <Thread(Thread-5 (serve_forever), started daemon 20392)>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 806, in serve_forever
    super().serve_forever(poll_interval=poll_interval)
                                        └ 0.5

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 237, in serve_forever
    self._handle_request_noblock()
    │    └ <function BaseServer._handle_request_noblock at 0x0000026B33257E20>
    └ <werkzeug.serving.BaseWSGIServer object at 0x0000026B359260E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
    │    │               │        └ ('127.0.0.1', 60055)
    │    │               └ <socket.socket fd=932, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=(...
    │    └ <function BaseServer.process_request at 0x0000026B34AA8040>
    └ <werkzeug.serving.BaseWSGIServer object at 0x0000026B359260E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 60055)
    │    │              └ <socket.socket fd=932, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=(...
    │    └ <function BaseServer.finish_request at 0x0000026B34AA8160>
    └ <werkzeug.serving.BaseWSGIServer object at 0x0000026B359260E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.BaseWSGIServer object at 0x0000026B359260E0>
    │    │                   │        └ ('127.0.0.1', 60055)
    │    │                   └ <socket.socket fd=932, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=(...
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.BaseWSGIServer object at 0x0000026B359260E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 747, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x0000026B35AA5900>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x0000026B3810B5E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 390, in handle
    super().handle()

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 432, in handle
    self.handle_one_request()
    │    └ <function BaseHTTPRequestHandler.handle_one_request at 0x0000026B34AA9870>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x0000026B3810B5E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 420, in handle_one_request
    method()
    └ <bound method WSGIRequestHandler.run_wsgi of <werkzeug.serving.WSGIRequestHandler object at 0x0000026B3810B5E0>>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <werkzeug.debug.DebuggedApplication object at 0x0000026B3810AC50>
    │       │    └ <werkzeug.serving.BaseWSGIServer object at 0x0000026B359260E0>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x0000026B3810B5E0>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x0000026B3821D7E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 325, in execute
    for data in application_iter:
                └ <generator object DebuggedApplication.debug_application at 0x0000026B381AAC70>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\debug\__init__.py", line 330, in debug_application
    app_iter = self.app(environ, start_response)
               │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x0000026B381AF2E0>
               │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=932>, 'wsgi.errors': <_io.TextIOWr...
               │    └ <Flask 'app'>
               └ <werkzeug.debug.DebuggedApplication object at 0x0000026B3810AC50>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x0000026B381AF2E0>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=932>, 'wsgi.errors': <_io.TextIOWr...
           │    └ <function Flask.wsgi_app at 0x0000026B35E07AC0>
           └ <Flask 'app'>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x0000026B35E07010>
               └ <Flask 'app'>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x0000026B35E06F80>
         └ <Flask 'app'>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           │    │           │    │              │    │            └ {}
           │    │           │    │              │    └ 'users.information'
           │    │           │    │              └ <Rule '/users/information' (POST, OPTIONS) -> users.information>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x0000026B369E5FC0>, 'apiversion.Apiversion': <function View.as_view...
           │    │           └ <Flask 'app'>
           │    └ <function Flask.ensure_sync at 0x0000026B35E07250>
           └ <Flask 'app'>

  File "E:\code\backend\api\api_1_0\usersResource\urls.py", line 25, in information
    return UsersOtherResource.information()
           │                  └ <classmethod(<function UsersOtherResource.information at 0x0000026B380FB9A0>)>
           └ <class 'api_1_0.usersResource.usersOtherResource.UsersOtherResource'>

  File "E:\code\backend\api\api_1_0\usersResource\usersOtherResource.py", line 80, in information
    res = UsersService.information(**kwargs)
          │            │             └ {'UserID': '2023120417239418', 'RealName': 'wang', 'Gender': '男', 'IDcard': '123', 'Address': '山西省吕梁市', 'Account': '123456', ...
          │            └ <classmethod(<function UsersService.information at 0x0000026B380FAB90>)>
          └ <class 'service.usersService.UsersService'>

> File "E:\code\backend\api\service\usersService.py", line 108, in information
    existing_user(RealName=realname,Gender=gender,IDcard=idcard,Address=address,Account=account,Email=email)
    │                      │               │             │              │               │             └ '2085616045@qq.com'
    │                      │               │             │              │               └ '123456'
    │                      │               │             │              └ '山西省吕梁市'
    │                      │               │             └ '123'
    │                      │               └ '男'
    │                      └ 'wang'
    └ <UsersService 2023120417239418>

TypeError: 'UsersService' object is not callable
2023-12-29 10:45:35.201 | ERROR    | utils.loggings:exception:40 - 'UserName'
Traceback (most recent call last):

  File "E:\pycharm\PyCharm2023.2.4\plugins\python\helpers\pydev\_pydev_bundle\pydev_monkey.py", line 805, in __call__
    ret = self.original_func(*self.args, **self.kwargs)
          │    │              │    │       │    └ {}
          │    │              │    │       └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x0000016D1424FA60>
          │    │              │    └ ()
          │    │              └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x0000016D1424FA60>
          │    └ <bound method Thread._bootstrap of <Thread(Thread-5 (serve_forever), started daemon 16412)>>
          └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x0000016D1424FA60>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x0000016D0ECC2E60>
    └ <Thread(Thread-5 (serve_forever), started daemon 16412)>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x0000016D0ECC2B90>
    └ <Thread(Thread-5 (serve_forever), started daemon 16412)>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-5 (serve_forever), started daemon 16412)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-5 (serve_forever), started daemon 16412)>
    │    └ <bound method BaseWSGIServer.serve_forever of <werkzeug.serving.BaseWSGIServer object at 0x0000016D11A260B0>>
    └ <Thread(Thread-5 (serve_forever), started daemon 16412)>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 806, in serve_forever
    super().serve_forever(poll_interval=poll_interval)
                                        └ 0.5

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 237, in serve_forever
    self._handle_request_noblock()
    │    └ <function BaseServer._handle_request_noblock at 0x0000016D0F357E20>
    └ <werkzeug.serving.BaseWSGIServer object at 0x0000016D11A260B0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
    │    │               │        └ ('127.0.0.1', 60086)
    │    │               └ <socket.socket fd=1108, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=...
    │    └ <function BaseServer.process_request at 0x0000016D10BA8040>
    └ <werkzeug.serving.BaseWSGIServer object at 0x0000016D11A260B0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 60086)
    │    │              └ <socket.socket fd=1108, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=...
    │    └ <function BaseServer.finish_request at 0x0000016D10BA8160>
    └ <werkzeug.serving.BaseWSGIServer object at 0x0000016D11A260B0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.BaseWSGIServer object at 0x0000016D11A260B0>
    │    │                   │        └ ('127.0.0.1', 60086)
    │    │                   └ <socket.socket fd=1108, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=...
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.BaseWSGIServer object at 0x0000016D11A260B0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 747, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x0000016D11BA5900>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x0000016D1421B5B0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 390, in handle
    super().handle()

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 432, in handle
    self.handle_one_request()
    │    └ <function BaseHTTPRequestHandler.handle_one_request at 0x0000016D10BA9870>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x0000016D1421B5B0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 420, in handle_one_request
    method()
    └ <bound method WSGIRequestHandler.run_wsgi of <werkzeug.serving.WSGIRequestHandler object at 0x0000016D1421B5B0>>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <werkzeug.debug.DebuggedApplication object at 0x0000016D1421AC20>
    │       │    └ <werkzeug.serving.BaseWSGIServer object at 0x0000016D11A260B0>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x0000016D1421B5B0>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x0000016D1431F0A0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 325, in execute
    for data in application_iter:
                └ <generator object DebuggedApplication.debug_application at 0x0000016D142B7290>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\debug\__init__.py", line 330, in debug_application
    app_iter = self.app(environ, start_response)
               │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x0000016D142BF2E0>
               │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=1108>, 'wsgi.errors': <_io.TextIOW...
               │    └ <Flask 'app'>
               └ <werkzeug.debug.DebuggedApplication object at 0x0000016D1421AC20>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x0000016D142BF2E0>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=1108>, 'wsgi.errors': <_io.TextIOW...
           │    └ <function Flask.wsgi_app at 0x0000016D11F07AC0>
           └ <Flask 'app'>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x0000016D11F07010>
               └ <Flask 'app'>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x0000016D11F06F80>
         └ <Flask 'app'>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           │    │           │    │              │    │            └ {}
           │    │           │    │              │    └ 'users.information'
           │    │           │    │              └ <Rule '/users/information' (OPTIONS, POST) -> users.information>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x0000016D12AE5FC0>, 'apiversion.Apiversion': <function View.as_view...
           │    │           └ <Flask 'app'>
           │    └ <function Flask.ensure_sync at 0x0000016D11F07250>
           └ <Flask 'app'>

  File "E:\code\backend\api\api_1_0\usersResource\urls.py", line 25, in information
    return UsersOtherResource.information()
           │                  └ <classmethod(<function UsersOtherResource.information at 0x0000016D142039A0>)>
           └ <class 'api_1_0.usersResource.usersOtherResource.UsersOtherResource'>

  File "E:\code\backend\api\api_1_0\usersResource\usersOtherResource.py", line 80, in information
    res = UsersService.information(**kwargs)
          │            │             └ {'UserID': '2023120417239418', 'RealName': 'wang', 'Gender': '男', 'IDcard': '123', 'Address': '山西省吕梁市', 'Account': '123456', ...
          │            └ <classmethod(<function UsersService.information at 0x0000016D14202B90>)>
          └ <class 'service.usersService.UsersService'>

> File "E:\code\backend\api\service\usersService.py", line 128, in information
    "RealName": user_info['UserName'],
                └ {'RealName': 'wang', 'Gender': '男'}

KeyError: 'UserName'
2023-12-29 10:47:30.290 | ERROR    | utils.loggings:exception:40 - 'UserName'
Traceback (most recent call last):

  File "E:\pycharm\PyCharm2023.2.4\plugins\python\helpers\pydev\_pydev_bundle\pydev_monkey.py", line 805, in __call__
    ret = self.original_func(*self.args, **self.kwargs)
          │    │              │    │       │    └ {}
          │    │              │    │       └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x0000025C7077FA90>
          │    │              │    └ ()
          │    │              └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x0000025C7077FA90>
          │    └ <bound method Thread._bootstrap of <Thread(Thread-5 (serve_forever), started daemon 16668)>>
          └ <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x0000025C7077FA90>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x0000025C6B1D2E60>
    └ <Thread(Thread-5 (serve_forever), started daemon 16668)>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x0000025C6B1D2B90>
    └ <Thread(Thread-5 (serve_forever), started daemon 16668)>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-5 (serve_forever), started daemon 16668)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-5 (serve_forever), started daemon 16668)>
    │    └ <bound method BaseWSGIServer.serve_forever of <werkzeug.serving.BaseWSGIServer object at 0x0000025C6DF660E0>>
    └ <Thread(Thread-5 (serve_forever), started daemon 16668)>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 806, in serve_forever
    super().serve_forever(poll_interval=poll_interval)
                                        └ 0.5

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 237, in serve_forever
    self._handle_request_noblock()
    │    └ <function BaseServer._handle_request_noblock at 0x0000025C6B897E20>
    └ <werkzeug.serving.BaseWSGIServer object at 0x0000025C6DF660E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
    │    │               │        └ ('127.0.0.1', 60123)
    │    │               └ <socket.socket fd=1084, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=...
    │    └ <function BaseServer.process_request at 0x0000025C6D0E8040>
    └ <werkzeug.serving.BaseWSGIServer object at 0x0000025C6DF660E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 60123)
    │    │              └ <socket.socket fd=1084, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=...
    │    └ <function BaseServer.finish_request at 0x0000025C6D0E8160>
    └ <werkzeug.serving.BaseWSGIServer object at 0x0000025C6DF660E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.BaseWSGIServer object at 0x0000025C6DF660E0>
    │    │                   │        └ ('127.0.0.1', 60123)
    │    │                   └ <socket.socket fd=1084, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5000), raddr=...
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.BaseWSGIServer object at 0x0000025C6DF660E0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 747, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x0000025C6E0E5900>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x0000025C7077FDC0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 390, in handle
    super().handle()

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 432, in handle
    self.handle_one_request()
    │    └ <function BaseHTTPRequestHandler.handle_one_request at 0x0000025C6D0E9870>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x0000025C7077FDC0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 420, in handle_one_request
    method()
    └ <bound method WSGIRequestHandler.run_wsgi of <werkzeug.serving.WSGIRequestHandler object at 0x0000025C7077FDC0>>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <werkzeug.debug.DebuggedApplication object at 0x0000025C7074EC50>
    │       │    └ <werkzeug.serving.BaseWSGIServer object at 0x0000025C6DF660E0>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x0000025C7077FDC0>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x0000025C7087CCA0>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 325, in execute
    for data in application_iter:
                └ <generator object DebuggedApplication.debug_application at 0x0000025C707E6F10>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\debug\__init__.py", line 330, in debug_application
    app_iter = self.app(environ, start_response)
               │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x0000025C7087CDC0>
               │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=1084>, 'wsgi.errors': <_io.TextIOW...
               │    └ <Flask 'app'>
               └ <werkzeug.debug.DebuggedApplication object at 0x0000025C7074EC50>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x0000025C7087CDC0>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=1084>, 'wsgi.errors': <_io.TextIOW...
           │    └ <function Flask.wsgi_app at 0x0000025C6E447AC0>
           └ <Flask 'app'>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x0000025C6E447010>
               └ <Flask 'app'>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x0000025C6E446F80>
         └ <Flask 'app'>

  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           │    │           │    │              │    │            └ {}
           │    │           │    │              │    └ 'users.information'
           │    │           │    │              └ <Rule '/users/information' (OPTIONS, POST) -> users.information>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x0000025C6F025FC0>, 'apiversion.Apiversion': <function View.as_view...
           │    │           └ <Flask 'app'>
           │    └ <function Flask.ensure_sync at 0x0000025C6E447250>
           └ <Flask 'app'>

  File "E:\code\backend\api\api_1_0\usersResource\urls.py", line 25, in information
    return UsersOtherResource.information()
           │                  └ <classmethod(<function UsersOtherResource.information at 0x0000025C707379A0>)>
           └ <class 'api_1_0.usersResource.usersOtherResource.UsersOtherResource'>

  File "E:\code\backend\api\api_1_0\usersResource\usersOtherResource.py", line 80, in information
    res = UsersService.information(**kwargs)
          │            │             └ {'UserID': '2023120417239418', 'RealName': 'wang', 'Gender': '男', 'IDcard': '123', 'Address': '山西省吕梁市', 'Account': '123456', ...
          │            └ <classmethod(<function UsersService.information at 0x0000025C70736B90>)>
          └ <class 'service.usersService.UsersService'>

> File "E:\code\backend\api\service\usersService.py", line 128, in information
    "RealName": user_info['UserName'],
                └ {'RealName': 'wang', 'Gender': '男'}

KeyError: 'UserName'
